# Generated by Django 3.2.12 on 2022-04-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
