# Generated by Django 3.2.12 on 2022-03-23 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('foreign_ghana', models.CharField(choices=[('f', 'Foreign Used'), ('g', 'Ghanaian Used')], max_length=1)),
                ('model', models.CharField(blank=True, choices=[('elantra', 'Elantra'), ('accent', 'Accent'), ('accord', 'Accord'), ('civic', 'Civic'), ('rav4', 'Rav4'), ('corolla', 'Corolla')], max_length=10)),
                ('make', models.CharField(blank=True, choices=[('hyundai', 'Hyundai'), ('honda', 'Honda'), ('toyota', 'Toyota')], max_length=10)),
                ('year_of_manufacture', models.IntegerField(choices=[(2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022)),
                ('body_type', models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('suv', 'Suv'), ('hatchback', 'Hatchback')], max_length=10)),
                ('mileage_km', models.IntegerField()),
                ('transmission', models.CharField(choices=[('a', 'Automatic'), ('m', 'Manual')], max_length=1)),
                ('fuel_type', models.CharField(choices=[('p', 'Petrol'), ('d', 'Diesel')], max_length=1)),
                ('engine_capacity', models.DecimalField(decimal_places=1, max_digits=2)),
                ('trim_edition', models.CharField(blank=True, choices=[('standard', 'Standard'), ('limited', 'Limited'), ('"full', '"Full'), ('option"', 'Option"'), ('XLE', 'Xle'), ('GT', 'Gt'), ('sport', 'Sport'), ('touring', 'Touring'), ('SE', 'Se'), ('LE', 'Le'), ('EX', 'Ex')], max_length=15)),
                ('location', models.CharField(choices=[('GA', 'Greater Accra'), ('VR', 'Volta Region'), ('ER', 'Eastern Region'), ('NR', 'Northern Region'), ('UE', 'Upper East Region'), ('UW', 'Upper West Region'), ('CR', 'Central Region')], max_length=2)),
                ('car_registered', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1)),
                ('registration_year', models.IntegerField(choices=[(2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022)),
                ('market_value', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
