# Generated by Django 3.2.12 on 2022-03-28 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_advertisement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='reporter',
            new_name='vendor',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='post_image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='AdvertisementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('advertisement', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='advertisements.advertisement')),
            ],
        ),
    ]
