# Generated by Django 3.2.12 on 2022-03-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_auto_20220328_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='selling_price',
            field=models.CharField(default=155000, max_length=50),
            preserve_default=False,
        ),
    ]
