# Generated by Django 3.2.12 on 2022-04-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_advertisement_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='selling_price',
            field=models.IntegerField(),
        ),
    ]
