# Generated by Django 3.2.12 on 2022-04-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0006_auto_20220406_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='post_image',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
