# Generated by Django 3.2.12 on 2022-04-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0007_alter_advertisement_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='make',
            field=models.CharField(blank=True, choices=[('hyundai', 'Hyundai'), ('honda', 'Honda'), ('toyota', 'Toyota')], max_length=20),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='model',
            field=models.CharField(blank=True, choices=[('elantra', 'Elantra'), ('accent', 'Accent'), ('accord', 'Accord'), ('civic', 'Civic'), ('rav4', 'Rav4'), ('corolla', 'Corolla')], max_length=20),
        ),
    ]
